In [2]:
import requests
import pandas as pd
import re
from collections import defaultdict  

def extract_album_id(album_link):
    match = re.search(r'/album/.*?/([\w-]+)\.html', album_link or "")
    return match.group(1) if match else "N/A"

def determine_album_type(track_count):
    if track_count <= 3:
        return "Single"
    elif 4 <= track_count <= 6:
        return "EP"
    else:
        return "Regular"

def fetch_artist_songs(artist_name):
    url = f"http://localhost:5000/api/artistsongs?name={artist_name}"
    response = requests.get(url)
    
    if response.status_code == 200:
        data = response.json()
        songs = data.get("songs", [])

        records = []
        album_tracks = defaultdict(set)  # Lưu các track duy nhất trong mỗi album

        for song in songs:
            album_id = extract_album_id(song.get("albumLink", "") or "")
            album_name = song.get("album", song.get("title", "N/A"))
            tracklist = song.get("tracklist", [])

            if not tracklist:
                tracklist = [{"title": song.get("title", "N/A"), "link": song.get("link", "N/A")}]

            for track in tracklist:
                track_title = track.get("title", "N/A")
                album_tracks[album_id].add(track_title)  # Lưu các track vào set để tránh trùng lặp

                records.append({
                    "album_id": album_id,
                    "album_name": album_name,
                    "tracklist": track_title,
                    "release_date": song.get("releaseDate", "Unknown"),
                    "provided_by": song.get("providedBy", "Unknown"),
                    "featured_artists": song.get("featuredArtists", "Unknown"),
                    "album_artist": song.get("albumOwner", "Unknown"),
                    "ZingMP3": track.get("link", "N/A")
                })

        df = pd.DataFrame(records)
        df = df.drop_duplicates(subset=["album_id", "tracklist"])  # Tránh bài hát trùng lặp
        df = df.sort_values(by=["album_name", "tracklist"], ascending=[True, True])

        # Thêm cột phân loại album dựa trên số lượng track thực tế
        df["album_type"] = df["album_id"].map(lambda x: determine_album_type(len(album_tracks[x])))

        return df
    else:
        print("Error fetching data:", response.status_code)
        return None

artist_name = 'Nghiem-Vu-Hoang-Long'
df = fetch_artist_songs(artist_name)
df.to_excel(f'{artist_name}_songZingMP3.xlsx', index=False)
df.head()

,album_id,album_name,tracklist,release_date,provided_by,featured_artists,album_artist,ZingMP3,album_type
42,6B8AWD98,99%,00,02/03/2023,The Orchard,MCK,MCK,https://zingmp3.vn/bai-hat/00-MCK/Z66CUCCA.html,Regular
49,6B8AWD98,99%,50/50,02/03/2023,The Orchard,MCK,MCK,https://zingmp3.vn/bai-hat/50-50-MCK/Z66CUCEW....,Regular
57,6B8AWD98,99%,99,02/03/2023,The Orchard,MCK,MCK,https://zingmp3.vn/bai-hat/99-MCK/Z66CUCF7.html,Regular
34,6B8AWD98,99%,Ai Mới Là Kẻ Xấu Xa,02/03/2023,The Orchard,MCK,MCK,https://zingmp3.vn/bai-hat/Ai-Moi-La-Ke-Xau-Xa...,Regular
23,6B8AWD98,99%,Anh Đã Ổn Hơn,02/03/2023,The Orchard,MCK,MCK,https://zingmp3.vn/bai-hat/Anh-Da-On-Hon-MCK/Z...,Regular

In [12]:
import requests
import pandas as pd
from collections import defaultdict

def fetch_artist_songs(artist_name):
    url = f"http://localhost:5000/api/artistsongs?name={artist_name}"
    response = requests.get(url)
    
    if response.status_code != 200:
        print("Error fetching data:", response.status_code)
        return None

    data = response.json()
    songs = data.get("songs", [])

    records = []
    album_tracks = defaultdict(set)

    for song in songs:
        album_link = song.get("albumLink", "")
        album_name = song.get("album") or song.get("title", "N/A")
        tracklist = song.get("tracklist") or [{"title": song.get("title", "N/A"), "link": song.get("link", "N/A")}]

        # Lấy album_type trực tiếp từ API (nếu có trong song data)
        album_type = song.get("albumType", "Unknown")
        
        # Lấy album_id từ song.albumId (giả sử dữ liệu albumId có sẵn)
        album_id = song.get("albumId", "Unknown")

        for track in tracklist:
            track_title = track.get("title", "N/A")
            album_tracks[album_id].add(track_title)

            records.append({
                "album_name": album_name,
                "tracklist": track_title,
                "release_date": song.get("releaseDate", "Unknown"),
                "provided_by": song.get("providedBy", "Unknown"),
                "featured_artists": song.get("featuredArtists", "Unknown"),
                "album_owner": song.get("albumOwner", "Unknown"),
                "album_id": album_id,
                "ZingMP3": track.get("link", "N/A"),
                "album_type": album_type
            })

    # Tạo DataFrame và xử lý dữ liệu
    df = pd.DataFrame(records)
    df.drop_duplicates(subset=["album_id", "tracklist"], inplace=True)
    df.sort_values(by=["album_name", "tracklist"], ascending=[True, True], inplace=True)

    return df

artist_name = 'Nghiem-Vu-Hoang-Long'
df = fetch_artist_songs(artist_name)
output_file = f'{artist_name}_songZingMP3.xlsx'
df.to_excel(output_file, index=False)
df.head()

,album_name,tracklist,release_date,provided_by,featured_artists,album_owner,album_id,ZingMP3,album_type
42,99%,00,02/03/2023,The Orchard,MCK,MCK,6B8AWD98,https://zingmp3.vn/bai-hat/00-MCK/Z66CUCCA.html,Regular
49,99%,50/50,02/03/2023,The Orchard,MCK,MCK,6B8AWD98,https://zingmp3.vn/bai-hat/50-50-MCK/Z66CUCEW....,Regular
57,99%,99,02/03/2023,The Orchard,MCK,MCK,6B8AWD98,https://zingmp3.vn/bai-hat/99-MCK/Z66CUCF7.html,Regular
35,99%,Ai Mới Là Kẻ Xấu Xa,02/03/2023,The Orchard,MCK,MCK,6B8AWD98,https://zingmp3.vn/bai-hat/Ai-Moi-La-Ke-Xau-Xa...,Regular
23,99%,Anh Đã Ổn Hơn,02/03/2023,The Orchard,MCK,MCK,6B8AWD98,https://zingmp3.vn/bai-hat/Anh-Da-On-Hon-MCK/Z...,Regular